name: env312
channels:
  - defaults
dependencies:
  - python=3.12
  - matplotlib
  - numpy
  - rasterio
  - pytorch
  - transformers
  - timm
  - diffusers
  - xformers
  - torchvision
  - pip
  - pip:
    - terratorch
    - granitewxc
